export const PatientFormDefaultValues = {
	firstName: "",
	lastName: "",
	email: "",
	phone: "",
	birthDate: new Date(Date.now()),
	gender: "male" as Gender,
	address: "",
	occupation: "",
	emergencyContactName: "",
	emergencyContactNumber: "",
	primaryPhysician: "",
	insuranceProvider: "",
	insurancePolicyNumber: "",
	allergies: "",
	currentMedication: "",
	familyMedicalHistory: "",
	pastMedicalHistory: "",
	identificationType: "",
	identificationNumber: "",
	identificationDocument: [],
	treatmentConsent: false,
	disclosureConsent: false,
	privacyConsent: false,
};

export const IdentificationTypes = [
	{ name: "Aadhaar card" },
	{ name: "Driver's License" },
	{ name: "Birth Certificate" },
	{ name: "Medical Insurance Card/Policy" },
	{ name: "Military ID Card" },
	{ name: "National Identity Card" },
	{ name: "Passport" },
	{ name: "Student ID Card" },
	{ name: "Voter ID Card" },
];
