export const dbConfig = {
	PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
	// API_KEY: process.env.NEXT_PUBLIC_API_KEY,
	DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID,
	PATIENT_COLLETION_ID: process.env.NEXT_PUBLIC_PATIENT_COLLETION_ID,
	DOCTOR_COLLECTION_ID: process.env.NEXT_PUBLIC_DOCTOR_COLLECTION_ID,
	DOCTOR_CALENDAR_COLLECTION_ID:
		process.env.NEXT_PUBLIC_DOCTOR_CALENDAR_COLLECTION_ID,
	APPOINTMENT_COLLECTION_ID: process.env.NEXT_PUBLIC_APPOINTMENT_COLLECTION_ID,
	BUCKET_ID: process.env.NEXT_PUBLIC_BUCKET_ID,
	ENDPOINT: process.env.NEXT_PUBLIC_ENDPOINT,
};
